[agent]
  flush_interval = "15s"
  interval = "15s"


# Input Plugins
[[inputs.net]]
[[inputs.ping]]
urls = ["google.de", "8.8.8.8"]
[[inputs.internet_speed]]
  interval = "300s"
# Output Plugin InfluxDB
[[outputs.influxdb]]
  database = "telegrafdb"
  urls = [ "http://influxdb:8086" ]
  username = "telegraf"
  password = "superInsecureInfluxPassword"
