volumes:
  influxdb_data:
  grafana_data:

services:
  influxdb:
    image: influxdb:1.8
    restart: always
    environment: 
      - INFLUXDB_DB=telegrafdb
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=superInsecureInfluxPassword
    volumes: 
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf:1.38.0
    restart: always
    volumes:
    - ./src/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
    - influxdb
    
  grafana:
    image: grafana/grafana:5.4.3
    restart: always
    volumes: 
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
